name: diary_journal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  table_calendar: ^3.0.0

  provider: ^6.0.3
  animated_splash_screen: ^1.3.0
  auto_route_generator: ^7.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  page_view_dot_indicator: ^2.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/


  # fonts:
  #   - family: KantumruyPro
  #     fonts:
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-ThinItalic.ttf
  #         weight: 100
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-ExtraLightItalic.ttf
  #         weight: 200
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-LightItalic.ttf
  #         weight: 300
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Italic.ttf
  #         weight: 400
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-MediumItalic.ttf
  #         weight: 500
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic

  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/kantumruy_pro/KantumruyPro-BoldItalic.ttf
  #         weight: 700
  #         style: italic


  #   - family: Poppins
  #     fonts:
  #       fonts:
  #       - asset: assets/fonts/poppins/Poppins-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
  #         weight: 100
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
  #         weight: 200
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
  #         weight: 300
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/poppins/Poppins-Italic.ttf
  #         weight: 400
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
  #         weight: 700
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic

  #       - asset: assets/fonts/poppins/Poppins-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
  #         weight: 900
  #         style: italic
